<?php
/**
 * Professional Grouped Sidebar Definitions for ISNM ERP
 * Each role gets a sidebar with MAIN, OPERATIONS, MANAGEMENT, REPORTS, COMMUNICATION, ACCOUNT groups.
 * Every group is collapsible. Only department-specific modules are listed.
 */
if (function_exists('getSidebarGroups')) return;

function getSidebarGroups(string $role): array {
    $roleKey = normalizeRoleKeySidebar($role);
    $execRoles = ['director_general','ceo','director_ict','director_academics','director_finance',
                  'director_admissions','principal','deputy_principal','academic_registrar'];
    $isExec = in_array($roleKey, $execRoles);

    $g = [];

    // ── MAIN ──
    $g['MAIN'] = [
        ['label' => 'Dashboard', 'icon' => 'fas fa-chart-pie', 'page' => 'home'],
    ];
    if ($isExec && $roleKey !== 'director_admissions') {
        $g['MAIN'][] = ['label' => 'Overview',  'icon' => 'fas fa-home',      'page' => 'overview'];
        $g['MAIN'][] = ['label' => 'Analytics', 'icon' => 'fas fa-chart-line','page' => 'analytics'];
    }

    // ── OPERATIONS (role-specific) ──
    $g['OPERATIONS'] = getRoleOperations($role);

    // ── MANAGEMENT (exec roles only) ──
    if ($isExec) {
        $g['MANAGEMENT'] = [
            ['label' => 'Approvals',    'icon' => 'fas fa-check-double', 'page' => 'approvals'],
            ['label' => 'Tasks',        'icon' => 'fas fa-tasks',       'page' => 'tasks'],
            ['label' => 'Schedules',    'icon' => 'fas fa-calendar-alt', 'page' => 'schedules'],
        ];
    }

    // ── REPORTS (exec roles only) ──
    if ($isExec && $roleKey !== 'director_admissions') {
        $g['REPORTS'] = [
            ['label' => 'Daily Reports',   'icon' => 'fas fa-calendar-day',  'page' => 'reports-daily'],
            ['label' => 'Monthly Reports', 'icon' => 'fas fa-calendar-alt',  'page' => 'reports-monthly'],
            ['label' => 'Annual Reports',  'icon' => 'fas fa-calendar-check','page' => 'reports-annual'],
            ['label' => 'Exports',         'icon' => 'fas fa-file-export',   'page' => 'exports'],
            ['label' => 'Print Center',    'icon' => 'fas fa-print',         'page' => 'print'],
        ];
    }

    // ── COMMUNICATION (all staff) ──
    $g['COMMUNICATION'] = [
        ['label' => 'Notifications', 'icon' => 'fas fa-bell',       'page' => 'notifications'],
        ['label' => 'Messages',      'icon' => 'fas fa-envelope',   'page' => 'communications', 'href' => 'communications.php'],
        ['label' => 'Announcements', 'icon' => 'fas fa-bullhorn',   'page' => 'announcements'],
    ];

    // ── ACCOUNT (everyone) ──
    $g['ACCOUNT'] = [
        ['label' => 'Profile',         'icon' => 'fas fa-user-circle', 'page' => 'profile'],
        ['label' => 'Preferences',     'icon' => 'fas fa-cog',         'page' => 'preferences'],
        ['label' => 'Security',        'icon' => 'fas fa-shield-alt',  'page' => 'security'],
        ['label' => 'Activity Logs',   'icon' => 'fas fa-history',     'page' => 'activity-logs'],
        ['label' => 'Logout',          'icon' => 'fas fa-sign-out-alt','page' => 'logout', 'href' => '../auth-handler.php?action=logout'],
    ];

    return $g;
}

function getRoleOperations(string $role): array {
    $roleKey = normalizeRoleKeySidebar($role);

    $definitions = [
        'director_general' => [
            ['label' => 'Department Monitoring','icon'=>'fas fa-building','page'=>'departments'],
            ['label' => 'Performance Dashboard','icon'=>'fas fa-chart-bar','page'=>'performance'],
            ['label' => 'Financial Overview',   'icon'=>'fas fa-coins',    'page'=>'financial'],
            ['label' => 'Staff Management',     'icon'=>'fas fa-users',    'page'=>'staff'],
            ['label' => 'Student Management',   'icon'=>'fas fa-user-graduate','page'=>'student'],
            ['label' => 'Intake Management',    'icon'=>'fas fa-door-open','page'=>'intake-management', 'href'=>'intake-management.php'],
            ['label' => 'Donation Tracking',    'icon'=>'fas fa-hand-holding-heart','page'=>'donation-tracking', 'href'=>'donation-tracking.php'],
            ['label' => 'Volunteer Applications','icon'=>'fas fa-hands-helping','page'=>'volunteer-applications', 'href'=>'volunteer-applications.php'],
            ['label' => 'System Health',        'icon'=>'fas fa-heartbeat','page'=>'system-health'],
            ['label' => 'Requirements Portal',   'icon'=>'fas fa-list-check','page'=>'director_requirements'],
            ['label' => 'News Management',      'icon'=>'fas fa-newspaper','page'=>'news-management'],
            ['label' => 'Events Management',    'icon'=>'fas fa-calendar','page'=>'events-mgmt'],
            ['label' => 'Testimonials',         'icon'=>'fas fa-quote-right','page'=>'testimonials-mgmt'],
            ['label' => 'FAQs Management',      'icon'=>'fas fa-question-circle','page'=>'faqs-mgmt'],
            ['label' => 'Website Settings',     'icon'=>'fas fa-globe','page'=>'web-settings'],
            ['label' => 'KPI Dashboard',        'icon'=>'fas fa-tachometer-alt','page'=>'kpi'],
            ['label' => 'Messaging',            'icon'=>'fas fa-comments','page'=>'messaging'],
            ['label' => 'Broadcast',            'icon'=>'fas fa-broadcast-tower','page'=>'broadcast'],
        ],
        'director_ict' => [
            ['label' => 'Assets & Inventory',   'icon'=>'fas fa-desktop',   'page'=>'assets'],
            ['label' => 'Infrastructure',       'icon'=>'fas fa-server',    'page'=>'infrastructure'],
            ['label' => 'Helpdesk',             'icon'=>'fas fa-ticket-alt','page'=>'helpdesk'],
            ['label' => 'Backups',              'icon'=>'fas fa-database',  'page'=>'backups'],
            ['label' => 'Security',             'icon'=>'fas fa-shield-alt','page'=>'security'],
            ['label' => 'Monitoring',           'icon'=>'fas fa-chart-line','page'=>'monitoring'],
            ['label' => 'Users & Access',       'icon'=>'fas fa-users',     'page'=>'users'],
            ['label' => 'ERP Management',       'icon'=>'fas fa-cogs',      'page'=>'erp'],
            ['label' => 'Website',              'icon'=>'fas fa-globe',     'page'=>'website'],
            ['label' => 'System Settings',      'icon'=>'fas fa-cog',       'page'=>'settings'],
        ],
        'director_academics' => [
            ['label' => 'Academic Programs',    'icon'=>'fas fa-book-open',    'page'=>'programs'],
            ['label' => 'Course Management',    'icon'=>'fas fa-book',         'page'=>'courses'],
            ['label' => 'Examinations',         'icon'=>'fas fa-pen',          'page'=>'exams'],
            ['label' => 'Timetable',            'icon'=>'fas fa-calendar-alt', 'page'=>'timetable'],
            ['label' => 'Clinical Training',    'icon'=>'fas fa-user-nurse',   'page'=>'clinical'],
            ['label' => 'Attendance',           'icon'=>'fas fa-calendar-check','page'=>'attendance'],
            ['label' => 'Quality Assurance',    'icon'=>'fas fa-check-circle', 'page'=>'quality'],
            ['label' => 'Academic Records',     'icon'=>'fas fa-clipboard-list','page'=>'academic_records'],
            ['label' => 'Reports Center',       'icon'=>'fas fa-chart-bar',    'page'=>'reports'],
        ],
        'director_finance' => [
            ['label' => 'Revenue Management',   'icon'=>'fas fa-arrow-up',     'page'=>'revenue'],
            ['label' => 'Budget Management',    'icon'=>'fas fa-calculator',   'page'=>'budget'],
            ['label' => 'Expenditure Control',  'icon'=>'fas fa-file-invoice', 'page'=>'expenditure'],
            ['label' => 'Payroll Oversight',    'icon'=>'fas fa-money-check',  'page'=>'payroll'],
            ['label' => 'Accounting & Ledger',  'icon'=>'fas fa-book',         'page'=>'ledger'],
            ['label' => 'Audit & Compliance',   'icon'=>'fas fa-clipboard-check','page'=>'audit'],
            ['label' => 'Procurement',          'icon'=>'fas fa-shopping-cart','page'=>'procurement'],
            ['label' => 'Assets & Investments', 'icon'=>'fas fa-building',     'page'=>'assets'],
        ],
        'director_admissions' => [
            ['label' => 'Overview',             'icon'=>'fas fa-chart-pie',     'page'=>'overview'],
            ['label' => 'Applicants',           'icon'=>'fas fa-users',        'page'=>'applicants'],
            ['label' => 'Requirements',         'icon'=>'fas fa-list-check',   'page'=>'requirements'],
            ['label' => 'Analytics',            'icon'=>'fas fa-chart-bar',    'page'=>'analytics'],
            ['label' => 'Registration',         'icon'=>'fas fa-user-graduate','page'=>'registration'],
            ['label' => 'Communications',       'icon'=>'fas fa-envelope',     'page'=>'communications'],
            ['label' => 'Online Submissions',   'icon'=>'fas fa-globe',        'page'=>'submissions'],
            ['label' => 'Reports',              'icon'=>'fas fa-file-alt',     'page'=>'reports'],
            ['label' => 'Student Records',      'icon'=>'fas fa-user-graduate','page'=>'students'],
            ['label' => 'Audit Log',            'icon'=>'fas fa-history',      'page'=>'activity'],
        ],
        'principal' => [
            ['label' => 'Dashboard',             'icon'=>'fas fa-home',              'page'=>'home'],
            ['label' => 'Academic Dashboard',    'icon'=>'fas fa-book-open',         'page'=>'academic'],
            ['label' => 'Program Performance',   'icon'=>'fas fa-chart-bar',         'page'=>'program-performance'],
            ['label' => 'Exam Monitoring',       'icon'=>'fas fa-file-alt',          'page'=>'exam-monitoring'],
            ['label' => 'Result Approvals',      'icon'=>'fas fa-check-double',      'page'=>'approvals'],
            ['label' => 'Clinical Training',     'icon'=>'fas fa-clinic-medical',    'page'=>'clinical-training'],
            ['label' => 'Academic Quality',      'icon'=>'fas fa-award',             'page'=>'academic-quality'],
            ['label' => 'Student Management',    'icon'=>'fas fa-users',             'page'=>'student'],
            ['label' => 'Student Welfare',       'icon'=>'fas fa-heart',             'page'=>'student-affairs'],
            ['label' => 'Discipline',            'icon'=>'fas fa-gavel',             'page'=>'discipline'],
            ['label' => 'Student Appeals',       'icon'=>'fas fa-file-contract',     'page'=>'student-appeals'],
            ['label' => 'Student Progress',      'icon'=>'fas fa-chart-line',        'page'=>'student-progress'],
            ['label' => 'Risk Indicators',       'icon'=>'fas fa-exclamation-triangle','page'=>'student-risk'],
            ['label' => 'Graduation Readiness',  'icon'=>'fas fa-graduation-cap',    'page'=>'graduation-readiness'],
            ['label' => 'Staff Overview',        'icon'=>'fas fa-user-tie',          'page'=>'staff'],
            ['label' => 'Staff Appraisals',      'icon'=>'fas fa-chart-pie',         'page'=>'staff-appraisals'],
            ['label' => 'Staff Development',     'icon'=>'fas fa-chalkboard-teacher','page'=>'staff-development'],
            ['label' => 'Strategic Plans',       'icon'=>'fas fa-flag',              'page'=>'strategic-plans'],
            ['label' => 'Institutional KPIs',    'icon'=>'fas fa-tachometer-alt',    'page'=>'institutional-kpis'],
            ['label' => 'Dept Performance',      'icon'=>'fas fa-building',          'page'=>'departments'],
            ['label' => 'Quality Assurance',     'icon'=>'fas fa-clipboard-check',   'page'=>'quality'],
            ['label' => 'Meetings',              'icon'=>'fas fa-handshake',         'page'=>'meetings'],
            ['label' => 'Action Tracking',       'icon'=>'fas fa-tasks',             'page'=>'tasks'],
            ['label' => 'Communications',        'icon'=>'fas fa-envelope',          'page'=>'notifications'],
            ['label' => 'News Management',       'icon'=>'fas fa-newspaper',         'page'=>'news-management', 'href'=>'news.php'],
            ['label' => 'Notices',               'icon'=>'fas fa-bullhorn',          'page'=>'notices'],
            ['label' => 'Announcements',         'icon'=>'fas fa-bullhorn',          'page'=>'announcements'],
            ['label' => 'Academic Reports',      'icon'=>'fas fa-file-alt',          'page'=>'reports-daily'],
            ['label' => 'Institutional Reports', 'icon'=>'fas fa-chart-area',        'page'=>'reports-monthly'],
        ],
        'deputy_principal' => [
            ['label' => 'Academic Monitoring',  'icon'=>'fas fa-book-open',    'page'=>'academic'],
            ['label' => 'Class Monitoring',     'icon'=>'fas fa-chalkboard',   'page'=>'classes'],
            ['label' => 'Student Welfare',      'icon'=>'fas fa-heart',        'page'=>'welfare'],
            ['label' => 'Student Discipline',   'icon'=>'fas fa-gavel',        'page'=>'discipline'],
            ['label' => 'Attendance',           'icon'=>'fas fa-calendar-check','page'=>'attendance'],
            ['label' => 'Clinical Placement',   'icon'=>'fas fa-clinic-medical','page'=>'clinical'],
            ['label' => 'Compliance Tracking',  'icon'=>'fas fa-check-circle', 'page'=>'compliance'],
            ['label' => 'Quality Assurance',    'icon'=>'fas fa-clipboard-check','page'=>'quality'],
        ],
        'academic_registrar' => [
            ['label' => 'Student Records',      'icon'=>'fas fa-folder-open',  'page'=>'student-records'],
            ['label' => 'Programs',             'icon'=>'fas fa-layer-group',  'page'=>'programs'],
            ['label' => 'Courses',              'icon'=>'fas fa-book',         'page'=>'courses'],
            ['label' => 'Examinations',         'icon'=>'fas fa-pen',          'page'=>'examinations'],
            ['label' => 'Results & Grades',     'icon'=>'fas fa-file-alt',     'page'=>'results'],
            ['label' => 'Transcripts',          'icon'=>'fas fa-file-invoice', 'page'=>'transcripts'],
            ['label' => 'Certificates',         'icon'=>'fas fa-certificate',  'page'=>'certificates'],
            ['label' => 'Graduation',           'icon'=>'fas fa-graduation-cap','page'=>'graduation'],
            ['label' => 'Timetable',            'icon'=>'fas fa-calendar-week','page'=>'timetable'],
            ['label' => 'Intakes',              'icon'=>'fas fa-door-open',    'page'=>'intakes'],
            ['label' => 'News Management',      'icon'=>'fas fa-newspaper',    'page'=>'news-management', 'href'=>'news.php'],
            ['label' => 'Exam Marks',           'icon'=>'fas fa-pen-fancy',    'page'=>'exam-marks', 'href'=>'academic-registrar.php?section=examinations'],
            ['label' => 'Grade Scales',         'icon'=>'fas fa-sort-numeric-up','page'=>'grade-scales', 'href'=>'academic-registrar.php?section=settings'],
            ['label' => 'Course Registration',  'icon'=>'fas fa-book-reader',  'page'=>'course-registration', 'href'=>'academic-registrar.php?section=courses'],
            ['label' => 'Student Library',      'icon'=>'fas fa-book-open',    'page'=>'student-library', 'href'=>'academic-registrar.php?section=student-records'],
        ],
        'secretary' => [
            ['label' => 'Dashboard',            'icon'=>'fas fa-home',          'page'=>'home'],
            ['label' => 'Student Registration', 'icon'=>'fas fa-user-plus',     'page'=>'student_registration'],
            ['label' => 'Student Records',      'icon'=>'fas fa-users',         'page'=>'student_records'],
            ['label' => 'Admissions',           'icon'=>'fas fa-clipboard-check','page'=>'admissions'],
            ['label' => 'Status Dashboard',     'icon'=>'fas fa-chart-bar',     'page'=>'status_dashboard'],
            ['label' => 'Reports',              'icon'=>'fas fa-file-alt',      'page'=>'reports'],
            ['label' => 'Correspondence',       'icon'=>'fas fa-envelope',      'page'=>'correspondence'],
            ['label' => 'Messages',             'icon'=>'fas fa-comments',      'page'=>'comms'],
            ['label' => 'Appointments',         'icon'=>'fas fa-calendar-check','page'=>'appointments'],
            ['label' => 'Meetings',             'icon'=>'fas fa-handshake',     'page'=>'meetings'],
            ['label' => 'Requests',             'icon'=>'fas fa-tasks',         'page'=>'requests'],
            ['label' => 'News Management',      'icon'=>'fas fa-newspaper',     'page'=>'news-management', 'href'=>'news.php'],
            ['label' => 'Announcements',        'icon'=>'fas fa-bullhorn',      'page'=>'announcements'],
            ['label' => 'Contacts',             'icon'=>'fas fa-address-book',  'page'=>'contacts'],
            ['label' => 'Document Management',  'icon'=>'fas fa-file-alt',      'page'=>'documents'],
            ['label' => 'Requirements Checklist','icon'=>'fas fa-clipboard-check','page'=>'requirements_checklist'],
            ['label' => 'General Utilities Store','icon'=>'fas fa-store',         'page'=>'store_items'],
            ['label' => 'Food Store Supplies',   'icon'=>'fas fa-utensils',      'page'=>'food_store'],
            ['label' => 'Matron Requisitions',   'icon'=>'fas fa-broom',         'page'=>'matron_requisitions'],
        ],
        'hr' => [
            ['label' => 'Overview',             'icon'=>'fas fa-chart-pie',   'page'=>'overview'],
            ['label' => 'Staff Records',        'icon'=>'fas fa-address-book','page'=>'staff'],
            ['label' => 'Attendance & Leave',   'icon'=>'fas fa-clipboard-list','page'=>'attendance'],
            ['label' => 'Payroll',              'icon'=>'fas fa-money-check', 'page'=>'payroll'],
            ['label' => 'Performance',          'icon'=>'fas fa-chart-line',  'page'=>'performance'],
            ['label' => 'Training & CPD',       'icon'=>'fas fa-graduation-cap','page'=>'training'],
            ['label' => 'Recruitment',          'icon'=>'fas fa-user-plus',   'page'=>'recruitment'],
            ['label' => 'Contracts',            'icon'=>'fas fa-file-contract','page'=>'contracts'],
            ['label' => 'Disciplinary',         'icon'=>'fas fa-gavel',       'page'=>'disciplinary'],
            ['label' => 'News Management',      'icon'=>'fas fa-newspaper',   'page'=>'news-management', 'href'=>'news.php'],
            ['label' => 'Communications',       'icon'=>'fas fa-comments',    'page'=>'communications'],
            ['label' => 'Reports',              'icon'=>'fas fa-file-alt',    'page'=>'reports'],
        ],
        'librarian' => [
            ['label' => 'Catalogue',            'icon'=>'fas fa-book',         'page'=>'catalogue'],
            ['label' => 'Books',                'icon'=>'fas fa-book-open',    'page'=>'books'],
            ['label' => 'Borrowing',            'icon'=>'fas fa-hand-holding', 'page'=>'borrowing'],
            ['label' => 'Returns',              'icon'=>'fas fa-undo',         'page'=>'returns'],
            ['label' => 'Reservations',         'icon'=>'fas fa-calendar-check','page'=>'reservations'],
            ['label' => 'Members',              'icon'=>'fas fa-id-card',      'page'=>'members'],
            ['label' => 'News Management',      'icon'=>'fas fa-newspaper',    'page'=>'news-management', 'href'=>'news.php'],
            ['label' => 'Barcodes',             'icon'=>'fas fa-qrcode',       'page'=>'barcodes'],
            ['label' => 'Inventory',            'icon'=>'fas fa-boxes',        'page'=>'inventory'],
            ['label' => 'Fines',                'icon'=>'fas fa-money-bill',   'page'=>'fines'],
        ],
        'head_nursing' => [
            ['label' => 'Department Overview',  'icon'=>'fas fa-chart-pie',    'page'=>'overview'],
            ['label' => 'Clinical Placements',  'icon'=>'fas fa-clinic-medical','page'=>'clinical'],
            ['label' => 'Nursing Students',     'icon'=>'fas fa-user-nurse',   'page'=>'students'],
            ['label' => 'Timetable',            'icon'=>'fas fa-calendar-week','page'=>'timetable'],
            ['label' => 'Courses',              'icon'=>'fas fa-book-open',    'page'=>'courses'],
            ['label' => 'News Management',      'icon'=>'fas fa-newspaper',    'page'=>'news-management', 'href'=>'news.php'],
            ['label' => 'Department Staff',     'icon'=>'fas fa-users',        'page'=>'staff'],
        ],
        'head_midwifery' => [
            ['label' => 'Department Overview',  'icon'=>'fas fa-chart-pie',    'page'=>'overview'],
            ['label' => 'Clinical Placements',  'icon'=>'fas fa-clinic-medical','page'=>'clinical'],
            ['label' => 'Midwifery Students',   'icon'=>'fas fa-baby',         'page'=>'students'],
            ['label' => 'Timetable',            'icon'=>'fas fa-calendar-week','page'=>'timetable'],
            ['label' => 'Courses',              'icon'=>'fas fa-book-open',    'page'=>'courses'],
            ['label' => 'News Management',      'icon'=>'fas fa-newspaper',    'page'=>'news-management', 'href'=>'news.php'],
            ['label' => 'Department Staff',     'icon'=>'fas fa-users',        'page'=>'staff'],
        ],
        'senior_lecturer' => [
            ['label' => 'Overview',             'icon'=>'fas fa-home',         'page'=>'overview'],
            ['label' => 'My Courses',           'icon'=>'fas fa-book',         'page'=>'my-courses'],
            ['label' => 'Timetable',            'icon'=>'fas fa-calendar-week','page'=>'timetable'],
            ['label' => 'Attendance',           'icon'=>'fas fa-calendar-check','page'=>'attendance'],
            ['label' => 'Marks Entry',          'icon'=>'fas fa-pen',          'page'=>'cat-marks'],
            ['label' => 'Exams',                'icon'=>'fas fa-file-alt',     'page'=>'exam-marks'],
            ['label' => 'Lecture Notes',        'icon'=>'fas fa-file-alt',     'page'=>'materials'],
            ['label' => 'Lesson Plans',         'icon'=>'fas fa-clipboard-list','page'=>'lesson-plans'],
            ['label' => 'Assignments',          'icon'=>'fas fa-tasks',        'page'=>'assignments'],
            ['label' => 'Results',              'icon'=>'fas fa-chart-bar',    'page'=>'results'],
            ['label' => 'Reports',              'icon'=>'fas fa-file-invoice', 'page'=>'reports'],
            ['label' => 'Research',             'icon'=>'fas fa-flask',        'page'=>'research'],
            ['label' => 'Announcements',        'icon'=>'fas fa-bullhorn',     'page'=>'announcements'],
        ],
        'lecturer' => [
            ['label' => 'Overview',             'icon'=>'fas fa-home',         'page'=>'overview'],
            ['label' => 'My Courses',           'icon'=>'fas fa-book',         'page'=>'my-courses'],
            ['label' => 'Schedule',             'icon'=>'fas fa-calendar-week','page'=>'timetable'],
            ['label' => 'Students',             'icon'=>'fas fa-users',        'page'=>'students'],
            ['label' => 'Assessments',          'icon'=>'fas fa-pen',          'page'=>'assessments'],
            ['label' => 'Grades',               'icon'=>'fas fa-file-alt',     'page'=>'grades'],
            ['label' => 'Resources',            'icon'=>'fas fa-folder-open',  'page'=>'materials'],
            ['label' => 'Communications',       'icon'=>'fas fa-comments',    'page'=>'communications'],
            ['label' => 'Student Records',      'icon'=>'fas fa-user-graduate','page'=>'student-records'],
            ['label' => 'Attendance',           'icon'=>'fas fa-calendar-check','page'=>'attendance'],
            ['label' => 'Results',              'icon'=>'fas fa-chart-bar',    'page'=>'results'],
            ['label' => 'Reports',              'icon'=>'fas fa-file-invoice','page'=>'reports'],
            ['label' => 'CAT Marks',            'icon'=>'fas fa-pen',          'page'=>'cat-marks'],
            ['label' => 'Exam Marks',           'icon'=>'fas fa-file-alt',     'page'=>'exam-marks'],
            ['label' => 'Lesson Plans',         'icon'=>'fas fa-clipboard-list','page'=>'lesson-plans'],
            ['label' => 'Assignments',          'icon'=>'fas fa-tasks',        'page'=>'assignments'],
        ],
        'matron' => [
            ['label' => 'Health Records',       'icon'=>'fas fa-notes-medical','page'=>'health-records'],
            ['label' => 'Hostel Management',    'icon'=>'fas fa-bed',          'page'=>'hostel'],
            ['label' => 'Meals & Accommodation','icon'=>'fas fa-utensils',     'page'=>'meals'],
            ['label' => 'Sick Bay',             'icon'=>'fas fa-plus-circle',  'page'=>'sickbay'],
            ['label' => 'Student Welfare',      'icon'=>'fas fa-heart',        'page'=>'welfare'],
            ['label' => 'Store Requisition',    'icon'=>'fas fa-clipboard-list','page'=>'store-requisition', 'href'=>'../store-requisition.php'],
        ],
        'wardens' => [
            ['label' => 'Hostel Management',    'icon'=>'fas fa-bed',          'page'=>'hostel'],
            ['label' => 'Discipline',           'icon'=>'fas fa-gavel',        'page'=>'discipline'],
            ['label' => 'Student Welfare',      'icon'=>'fas fa-heart',        'page'=>'welfare'],
            ['label' => 'Hostel Reports',       'icon'=>'fas fa-file-alt',     'page'=>'reports'],
            ['label' => 'Store Requisition',    'icon'=>'fas fa-clipboard-list','page'=>'store-requisition', 'href'=>'../store-requisition.php'],
        ],
        'drivers' => [
            ['label' => 'Dashboard',           'icon'=>'fas fa-home',            'page'=>'home'],
            ['label' => 'Vehicles',            'icon'=>'fas fa-truck',           'page'=>'transport-vehicles', 'href'=>'drivers.php?page=transport-vehicles'],
            ['label' => 'Routes',              'icon'=>'fas fa-route',           'page'=>'transport-routes',   'href'=>'drivers.php?page=transport-routes'],
            ['label' => 'Trips',               'icon'=>'fas fa-map-marked-alt',  'page'=>'transport-trips',    'href'=>'drivers.php?page=transport-trips'],
            ['label' => 'Student Transport',   'icon'=>'fas fa-user-graduate',   'page'=>'student-transport',  'href'=>'drivers.php?page=student-transport'],
            ['label' => 'Fuel Log',            'icon'=>'fas fa-gas-pump',        'page'=>'fuel-log',           'href'=>'drivers.php?page=fuel-log'],
            ['label' => 'Reports',             'icon'=>'fas fa-file-alt',        'page'=>'reports',            'href'=>'drivers.php?page=reports'],
            ['label' => 'Store Requisition',   'icon'=>'fas fa-clipboard-list',  'page'=>'store-requisition',  'href'=>'store-requisition.php'],
        ],
        'security' => [
            ['label' => 'Overview',            'icon'=>'fas fa-chart-pie',        'page'=>'overview'],
            ['label' => 'Visitors',            'icon'=>'fas fa-user-plus',       'page'=>'visitors'],
            ['label' => 'Incident Reports',    'icon'=>'fas fa-exclamation-triangle','page'=>'incidents'],
            ['label' => 'Patrol Management',   'icon'=>'fas fa-shield-alt',      'page'=>'patrol'],
            ['label' => 'Access Control',      'icon'=>'fas fa-key',             'page'=>'access_control'],
            ['label' => 'Emergency Contacts',  'icon'=>'fas fa-ambulance',       'page'=>'emergency'],
            ['label' => 'Store Requisition',   'icon'=>'fas fa-clipboard-list',  'page'=>'store-requisition', 'href'=>'store-requisition.php'],
        ],
        'store' => [
            ['label' => 'Dashboard',            'icon'=>'fas fa-home',         'page'=>'dashboard'],
            ['label' => 'Inventory',            'icon'=>'fas fa-boxes',        'page'=>'inventory'],
            ['label' => 'Categories',           'icon'=>'fas fa-tags',         'page'=>'categories'],
            ['label' => 'Store Requests',       'icon'=>'fas fa-clipboard-list','page'=>'requests'],
            ['label' => 'Transactions',         'icon'=>'fas fa-history',      'page'=>'transactions'],
        ],
        'computer_lab' => [
            ['label' => 'Dashboard',            'icon'=>'fas fa-home',         'page'=>'dashboard'],
            ['label' => 'Computers',            'icon'=>'fas fa-desktop',      'page'=>'computers'],
            ['label' => 'Lab Sessions',         'icon'=>'fas fa-calendar-check','page'=>'sessions'],
            ['label' => 'Equipment',            'icon'=>'fas fa-tools',        'page'=>'equipment'],
            ['label' => 'Consumables',          'icon'=>'fas fa-boxes',        'page'=>'inventory'],
            ['label' => 'ID Cards',             'icon'=>'fas fa-id-card',      'page'=>'id-cards'],
            ['label' => 'Attendance',           'icon'=>'fas fa-calendar-check','page'=>'attendance'],
            ['label' => 'Printing Centre',      'icon'=>'fas fa-print',        'page'=>'printing'],
            ['label' => 'Support Tickets',      'icon'=>'fas fa-headset',      'page'=>'support'],
            ['label' => 'Software',             'icon'=>'fas fa-code',         'page'=>'software'],
            ['label' => 'Reports',              'icon'=>'fas fa-file-alt',     'page'=>'reports'],
            ['label' => 'Settings',             'icon'=>'fas fa-cog',          'page'=>'settings'],
        ],
        'skills_lab' => [
            ['label' => 'Overview',             'icon'=>'fas fa-home',         'page'=>'home'],
            ['label' => 'Equipment',            'icon'=>'fas fa-tools',        'page'=>'equipment'],
            ['label' => 'Checkouts',            'icon'=>'fas fa-hand-holding', 'page'=>'checkouts'],
            ['label' => 'Practical Sessions',   'icon'=>'fas fa-flask',        'page'=>'sessions'],
            ['label' => 'Skills',               'icon'=>'fas fa-star',         'page'=>'skills'],
            ['label' => 'Consumables',          'icon'=>'fas fa-boxes',        'page'=>'consumables'],
            ['label' => 'Attendance',           'icon'=>'fas fa-calendar-check','page'=>'attendance'],
            ['label' => 'Incidents',            'icon'=>'fas fa-exclamation-triangle','page'=>'incidents'],
        ],
        'guild' => [
            ['label' => 'Student Body',         'icon'=>'fas fa-users',        'page'=>'student-body'],
            ['label' => 'Student Welfare',      'icon'=>'fas fa-heart',        'page'=>'welfare'],
            ['label' => 'Events',               'icon'=>'fas fa-calendar-alt', 'page'=>'events'],
            ['label' => 'Feedback',             'icon'=>'fas fa-comment-dots', 'page'=>'feedback'],
            ['label' => 'Guild Reports',        'icon'=>'fas fa-file-alt',     'page'=>'reports'],
        ],
        'bursar' => [
            ['label' => 'Dashboard',            'icon'=>'fas fa-chart-pie',    'page'=>'overview'],
            ['label' => 'Billing & Fees',       'icon'=>'fas fa-file-invoice', 'page'=>'billing'],
            ['label' => 'Payments',             'icon'=>'fas fa-money-bill',   'page'=>'payments'],
            ['label' => 'Reports',              'icon'=>'fas fa-chart-bar',    'page'=>'reports'],
            ['label' => 'Budget & Expenses',    'icon'=>'fas fa-calculator',   'page'=>'budget'],
            ['label' => 'Payroll',              'icon'=>'fas fa-users-cog',    'page'=>'payroll'],
            ['label' => 'General Ledger',       'icon'=>'fas fa-book',         'page'=>'ledger'],
            ['label' => 'Inventory & Assets',   'icon'=>'fas fa-boxes',        'page'=>'inventory'],
            ['label' => 'News Management',      'icon'=>'fas fa-newspaper',    'page'=>'news-management', 'href'=>'news.php'],
            ['label' => 'Communications',       'icon'=>'fas fa-comments',     'page'=>'communications'],
            ['label' => 'URA Tax',              'icon'=>'fas fa-calculator',   'page'=>'ura'],
            ['label' => 'Payment Providers',    'icon'=>'fas fa-credit-card',  'page'=>'payment-providers'],
        ],
        'ceo' => [
            ['label' => 'Overview',             'icon'=>'fas fa-chart-pie',    'page'=>'overview'],
            ['label' => 'Department Monitoring','icon'=>'fas fa-building',    'page'=>'departments'],
            ['label' => 'Performance Dashboard','icon'=>'fas fa-chart-bar',   'page'=>'performance'],
            ['label' => 'Financial Overview',   'icon'=>'fas fa-coins',       'page'=>'financial'],
            ['label' => 'Staff Management',     'icon'=>'fas fa-users',       'page'=>'staff'],
            ['label' => 'Student Management',   'icon'=>'fas fa-user-graduate','page'=>'student'],
            ['label' => 'Quality Assurance',    'icon'=>'fas fa-shield-alt',  'page'=>'quality'],
            ['label' => 'Audit Trail',          'icon'=>'fas fa-clipboard-check','page'=>'audit'],
            ['label' => 'System Health',        'icon'=>'fas fa-heartbeat',   'page'=>'system-health'],
            ['label' => 'Executive Reports',    'icon'=>'fas fa-file-alt',    'page'=>'reports', 'href'=>'financial-reports.php'],
        ],
        'non_teaching' => [
            ['label' => 'Overview',             'icon'=>'fas fa-home',             'page'=>'overview'],
            ['label' => 'My Tasks',             'icon'=>'fas fa-tasks',            'page'=>'tasks'],
            ['label' => 'My Attendance',        'icon'=>'fas fa-calendar-check',   'page'=>'attendance'],
            ['label' => 'Leave Management',     'icon'=>'fas fa-calendar-alt',     'page'=>'leave'],
            ['label' => 'Documents',            'icon'=>'fas fa-folder-open',      'page'=>'documents'],
            ['label' => 'Training',             'icon'=>'fas fa-graduation-cap',   'page'=>'training'],
            ['label' => 'Communications',       'icon'=>'fas fa-comments',         'page'=>'communications'],
            ['label' => 'Recent Activities',    'icon'=>'fas fa-history',          'page'=>'activities'],
        ],
        'student' => [
            ['label' => 'Dashboard',            'icon'=>'fas fa-th-large',       'page'=>'dashboard'],
            ['label' => 'My Profile',           'icon'=>'fas fa-user-circle',    'page'=>'profile'],
            ['label' => 'Academic Record',      'icon'=>'fas fa-graduation-cap','page'=>'academics'],
            ['label' => 'Course Registration',  'icon'=>'fas fa-book',          'page'=>'courses'],
            ['label' => 'Results & Transcripts','icon'=>'fas fa-file-alt',      'page'=>'results'],
            ['label' => 'Attendance',           'icon'=>'fas fa-clipboard-check','page'=>'attendance'],
            ['label' => 'Clinical Placement',   'icon'=>'fas fa-hospital',      'page'=>'clinical'],
            ['label' => 'Logbook',              'icon'=>'fas fa-book-open',     'page'=>'logbook'],
            ['label' => 'Competencies',         'icon'=>'fas fa-star',          'page'=>'competency'],
            ['label' => 'Requirements',         'icon'=>'fas fa-check-double',  'page'=>'requirements'],
            ['label' => 'Discipline',           'icon'=>'fas fa-gavel',         'page'=>'discipline'],
            ['label' => 'Finances',             'icon'=>'fas fa-money-bill',    'page'=>'finances'],
            ['label' => 'Hostel',               'icon'=>'fas fa-home',          'page'=>'hostel'],
            ['label' => 'Library',              'icon'=>'fas fa-book-reader',   'page'=>'library'],
            ['label' => 'Announcements',        'icon'=>'fas fa-bullhorn',      'page'=>'notices'],
            ['label' => 'Messages',             'icon'=>'fas fa-envelope',      'page'=>'messages'],
            ['label' => 'My Requests',          'icon'=>'fas fa-paper-plane',   'page'=>'requests'],
            ['label' => 'My Timetable',         'icon'=>'fas fa-calendar-alt',  'page'=>'timetable'],
        ],
        'system_admin' => [
            ['label' => 'Dashboard',            'icon'=>'fas fa-tachometer-alt',   'page'=>'dashboard'],
            ['label' => 'User Management',      'icon'=>'fas fa-users-cog',        'page'=>'users'],
            ['label' => 'Roles & Permissions',  'icon'=>'fas fa-shield-alt',       'page'=>'roles'],
            ['label' => 'System Backup',        'icon'=>'fas fa-database',         'page'=>'backup'],
            ['label' => 'Audit Logs',           'icon'=>'fas fa-clipboard-list',   'page'=>'audit'],
            ['label' => 'System Settings',      'icon'=>'fas fa-cog',              'page'=>'settings'],
            ['label' => 'Recycle Bin',          'icon'=>'fas fa-trash-restore',    'page'=>'recycle'],
        ],
        'sickbay' => [
            ['label' => 'Dashboard',            'icon'=>'fas fa-tachometer-alt', 'page'=>'dashboard'],
            ['label' => 'Daily Sick Records',   'icon'=>'fas fa-notes-medical',  'page'=>'daily-records'],
            ['label' => 'Sickness Directory',   'icon'=>'fas fa-disease',       'page'=>'sickness'],
            ['label' => 'Leave Sheet',          'icon'=>'fas fa-file-medical',  'page'=>'leave'],
            ['label' => 'Medicine Stock',       'icon'=>'fas fa-capsules',      'page'=>'medicine'],
            ['label' => 'Health Records',       'icon'=>'fas fa-notes-medical',  'page'=>'health-records'],
            ['label' => 'Health Incidents',     'icon'=>'fas fa-exclamation-triangle','page'=>'health-incidents'],
            ['label' => 'Sickbay Visits',       'icon'=>'fas fa-clipboard-list','page'=>'visits'],
            ['label' => 'Audit Trail',          'icon'=>'fas fa-history',       'page'=>'audit'],
            ['label' => 'Settings',             'icon'=>'fas fa-cog',           'page'=>'settings'],
        ],
        'events' => [
            ['label' => 'Dashboard',            'icon'=>'fas fa-chart-pie',     'page'=>'overview'],
            ['label' => 'Calendar',             'icon'=>'fas fa-calendar-alt',  'page'=>'calendar'],
            ['label' => 'All Events',           'icon'=>'fas fa-calendar-day',  'page'=>'events'],
            ['label' => 'Event Categories',     'icon'=>'fas fa-tags',          'page'=>'categories'],
            ['label' => 'Attendees',            'icon'=>'fas fa-users',         'page'=>'attendees'],
            ['label' => 'Reports',              'icon'=>'fas fa-file-alt',      'page'=>'reports'],
            ['label' => 'Settings',             'icon'=>'fas fa-cog',           'page'=>'settings'],
        ],
        'alumni' => [
            ['label' => 'Dashboard',            'icon'=>'fas fa-chart-pie',     'page'=>'overview'],
            ['label' => 'Alumni Directory',     'icon'=>'fas fa-address-book',  'page'=>'alumni'],
            ['label' => 'Contributions',        'icon'=>'fas fa-hand-holding-usd','page'=>'contributions'],
            ['label' => 'Job Board',            'icon'=>'fas fa-briefcase',     'page'=>'jobs'],
            ['label' => 'Alumni Events',        'icon'=>'fas fa-calendar-alt',  'page'=>'events'],
            ['label' => 'Reports',              'icon'=>'fas fa-file-alt',      'page'=>'reports'],
            ['label' => 'Settings',             'icon'=>'fas fa-cog',           'page'=>'settings'],
        ],
    ];

    return $definitions[$roleKey] ?? $definitions['lecturer'];
}

function normalizeRoleKeySidebar(string $role): string {
    $m = strtolower(trim($role));
    $map = [
        'director general' => 'director_general', 'ceo' => 'ceo', 'chief executive officer' => 'ceo', 'executive director' => 'ceo',
        'director ict' => 'director_ict', 'director academics' => 'director_academics',
        'director admissions' => 'director_admissions', 'director admissions & requirements' => 'director_admissions', 'admissions' => 'director_admissions', 'admissions officer' => 'director_admissions', 'admissions clerk' => 'director_admissions',
        'director finance' => 'director_finance',
        'school principal' => 'principal', 'deputy principal' => 'deputy_principal',
        'academic registrar' => 'academic_registrar', 'school secretary' => 'secretary',
        'hr manager' => 'hr', 'school librarian' => 'librarian', 'librarian' => 'librarian',
        'head of nursing' => 'head_nursing', 'head nursing' => 'head_nursing', 'head nursing department' => 'head_nursing', 'hod' => 'head_nursing', 'head of department' => 'head_nursing',
        'head of midwifery' => 'head_midwifery', 'head midwifery' => 'head_midwifery', 'head midwifery department' => 'head_midwifery',
        'senior lecturer' => 'senior_lecturer', 'senior lecturers' => 'senior_lecturer',
        'lecturer' => 'lecturer', 'lecturers' => 'lecturer',
        'matron' => 'matron', 'matrons' => 'matron',
        'warden' => 'wardens', 'wardens' => 'wardens',
        'driver' => 'drivers', 'drivers' => 'drivers', 'transport officer' => 'drivers',
        'security' => 'security', 'security officer' => 'security',
        'storekeeper' => 'store', 'store keeper' => 'store',
        'computer lab' => 'computer_lab', 'computer lab manager' => 'computer_lab', 'computer laboratory' => 'computer_lab',
        'skills lab' => 'skills_lab', 'skills lab manager' => 'skills_lab', 'skills lab technician' => 'skills_lab', 'skills laboratory' => 'skills_lab',
        'guild president' => 'guild',
        'school bursar' => 'bursar', 'bursar' => 'bursar',
        'sickbay' => 'sickbay', 'sickbay nurse' => 'sickbay', 'sick_bay' => 'sickbay', 'nurse' => 'sickbay',
        'non-teaching' => 'non_teaching', 'non-teaching-staff' => 'non_teaching', 'non teaching' => 'non_teaching', 'non teaching staff' => 'non_teaching', 'non_teaching' => 'non_teaching', 'non teaching staff' => 'non_teaching',
        'system admin' => 'system_admin', 'system-admin' => 'system_admin', 'system_admin' => 'system_admin', 'system administrator' => 'system_admin', 'admin' => 'system_admin', 'administrator' => 'system_admin',
        'student' => 'student', 'students' => 'student',
        'events coordinator' => 'events', 'events manager' => 'events',
        'alumni relations officer' => 'alumni', 'alumni officer' => 'alumni',
        'clinical placement officer' => 'academic_registrar',
        'quality assurance officer' => 'senior_lecturer',
        'lab technician' => 'skills_lab',
        'ict officer' => 'director_ict', 'ict_officer' => 'director_ict', 'ict' => 'director_ict',
        'events coordinator' => 'events', 'events manager' => 'events',
        'alumni relations officer' => 'alumni', 'alumni officer' => 'alumni',
    ];
    return $map[$m] ?? 'lecturer';
}
